apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: forum-backend
  template:
    metadata:
      labels:
        app: forum-backend
    spec:
      containers:
      - name: backend
        image: forum-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URI
          value: "mongodb://mongo:27017/forum"
        - name: PORT
          value: "5000"